###################################
# API GATEWAY
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: us-central1-docker.pkg.dev/abcall/abcall/api-gateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: GESTOR_CLIENTES_BASE_URL
              value: http://servicio-gestor-clientes
            - name: GENERACION_REPORTES_BASE_URL
              value: http://servicio-generacion-reportes
            - name: GESTOR_INCIDENTES_BASE_URL
              value: http://servicio-gestor-incidentes
            - name: GESTOR_FIDELIZACION_BASE_URL
              value: http://servicio-gestor-fidelizacion
            - name: DATABASE_URL
              valueFrom:
                  secretKeyRef:
                    name: app-secrets 
                    key: DATABASE_URL
            - name: GESTOR_AGENTES_BASE_URL
              value: http://servicio-gestor-agentes
            - name: OPENAI_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: OPENAI_API_KEY
            - name: EMAIL_ADDRESS
              valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: EMAIL_ADDRESS
            - name: EMAIL_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: app-secrets
                    key: EMAIL_PASSWORD
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5000
    type: HTTP
    requestPath: /api-gateway/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-api-gateway
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-config"}'
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31030

---
###################################
# gestor-agentes
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-agentes
  labels:
    app: gestor-agentes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestor-agentes
  template:
    metadata:
      labels:
        app: gestor-agentes
    spec:
      containers:
        - name: gestor-agentes
          image: us-central1-docker.pkg.dev/abcall/abcall/gestor-agentes:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                  secretKeyRef:
                    name: app-secrets 
                    key: DATABASE_URL
          imagePullPolicy: Always

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gestor-agentes-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5000
    type: HTTP
    requestPath: /gestor-agentes/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-gestor-agentes
  annotations:
    cloud.google.com/backend-config: '{"default": "gestor-agentes-config"}'
spec:
  type: NodePort
  selector:
    app: gestor-agentes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31026
---
###################################
# gestor-incidentes
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-incidentes
  labels:
    app: gestor-incidentes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestor-incidentes
  template:
    metadata:
      labels:
        app: gestor-incidentes
    spec:
      containers:
        - name: gestor-incidentes
          image: us-central1-docker.pkg.dev/abcall/abcall/gestor-incidentes:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                  secretKeyRef:
                    name: app-secrets 
                    key: DATABASE_URL
          imagePullPolicy: Always

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gestor-incidentes-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5000
    type: HTTP
    requestPath: /gestor-incidentes/ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-gestor-incidentes
  annotations:
    cloud.google.com/backend-config: '{"default": "gestor-incidentes-config"}'
spec:
  type: NodePort
  selector:
    app: gestor-incidentes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31023
---