name: formatting on PRs
on:
  pull_request:
    types: 
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [develop]

permissions:
  contents: write

jobs:
  formatting:
    name: Formateo de código
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar Black
        run: pip install black
      - name: Formateo de código con Black
        run: black .

  tests_api_gateway:
    name: Pruebas para api-gateway
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Ejecutar pruebas
        working-directory: api-gateway
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"

  tests_generacion_reportes:
    name: Pruebas para generacion-reportes
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Ejecutar pruebas
        working-directory: generacion-reportes
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"

  tests_gestor_agentes:
    name: Pruebas para gestor-agentes
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Ejecutar pruebas
        working-directory: gestor-agentes
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"


  tests_gestor_incidentes:
    name: Pruebas para gestor-incidentes
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuración del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Configurar Firebase Credentials
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "${FIREBASE_CREDENTIALS}" > /tmp/firebase-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-credentials.json" >> $GITHUB_ENV
      - name: Ejecutar pruebas
        working-directory: gestor-incidentes
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-credentials.json
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"

  commit_cambios_black:
    name: Commit de los resultados de Black
    runs-on: ubuntu-latest
    needs: 
      - formatting
      - tests_api_gateway
      - tests_generacion_reportes
      - tests_gestor_agentes
      - tests_gestor_incidentes
    steps:
      - name: Commit de los cambios
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Formateo automático de código en PRs"