name: Release
on:
  push:
    branches: 
      - 'release**'
jobs:    
  tests_api_gateway:
    name: Pruebas para api-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuraci贸n del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Ejecutar pruebas
        working-directory: api-gateway
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"

  tests_generacion_reportes:
    name: Pruebas para generacion-reportes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuraci贸n del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Ejecutar pruebas
        working-directory: generacion-reportes
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"

  tests_gestor_agentes:
    name: Pruebas para gestor-agentes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuraci贸n del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Ejecutar pruebas
        working-directory: gestor-agentes
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"


  tests_gestor_incidentes:
    name: Pruebas para gestor-incidentes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Configuraci贸n del entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Ejecutar pruebas
        working-directory: gestor-incidentes
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest
      - name: Validar resultado con errores
        if: ${{ failure() }}
        run: echo "Una o varias pruebas fallaron"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        run: echo "Todas las pruebas fueron exitosas"

  automerge:
    name: Automerge
    needs: 
      - tests_api_gateway
      - tests_generacion_reportes
      - tests_gestor_agentes
      - tests_gestor_incidentes
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
      - name: merge with develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: releases/${{ github.ref }}
          target-branch: develop
      - name: merge with main
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: releases/${{ github.ref }}
          target-branch: main